### ISSUE TITLE
Changelog doesn't indicate why new permissions for `Access browser tabs` is required

### ISSUE THREAD

**Issue by geeknik** [conceptualspace/enhance-o-tron-for-plex#5]
Hello, looking through the git commits and the changelog, there is no indication why a new permission for `Access browser tabs` is required. 1.5.3 is currently installed and works perfectly fine without granting extra permissions. 
![image](https://user-images.githubusercontent.com/466878/146773734-5a9eb718-e7f0-47e8-89fa-b9706686aff6.png)

![image](https://user-images.githubusercontent.com/466878/146773591-c8d32768-a579-413a-82ba-e8379530ebff.png)
Thank you.

**Comment by conceptualspace** [comment]
earlier versions of enhanceotron only worked on 3 hardcoded domains: app.plex.tv, localhost, and 127.0.0.1. in order to support custom domains (some people run their plex server on a machine on their LAN for instance) without having to grant access to ALL_URLS, we use the more limited tabs permission. this way enhanceotron can request permissions for a specific domain and will only run on that url.

to see how this works, look at line 15 in [background.js](https://github.com/conceptualspace/enhance-o-tron-for-plex/blob/4661580bfa278437b79e6d5e3ce430584b3a1d66/src/background.js#L15)

note that due to differences in implementation, we actually don't need the tabs permission on chrome to do this, but we do on firefox.

hope that answers your question! cheers
